#!/bin/bash
# Script to upload tv shows and movies to GCD
# Import common functions
source /opt/plexgsuite/plexgcd.func
# Import functions
source /opt/plexgsuite/plexgcd.conf

uploadtv() {
  rclone move --exclude partial~ --log-file=/opt/plexgsuite/logs/rclone-tv-gcd.log -v --transfers 10 --drive-chunk-size=16M /data/.local/tvshows/ gcd-crypt:tvshows/
}

uploadmv() {
  rclone move --exclude partial~ --log-file=/opt/plexgsuite/logs/rclone-movie-gcd.log -v --transfers 10 --drive-chunk-size=16M /data/.local/movies/ gcd-crypt:movies/
}

main() {
    lock $PROGNAME \
        || eexit "Only one instance of $PROGNAME can run at one time."

    logsetup
    # Pause nzbget for fastest upload
    pause_nzbget
    # Upload TV Shows
    uploadtv
    uploadmv
    # Resume nzbget
    resume_nzbget

    rm /opt/plexgsuite/uploadgcd.lock
}

# Execute functions inside main, will providing locking to avoid multiple scripts running at same time
main
